---
layout: page
title: Research
permalink: /research/
---
I am interested on Bayesian Statistics, currently my work focus on studying Approximate Bayesian Computation methods and for the master written component I've worked on making bayesian inference for a covariance matrix.

# Publications:

* Ignacio Alvarez, Jarad Niemi, and Matt Simpson. "Bayesian inference for a covariance matrix" Accepted in the Proceedings for the Conference on Applied Statistics in Agriculture.  

* Natalia da Silva, and Ignacio Alvarez. "Clique and Clicks. Exploring the soul of the community". Accepted in Computational Statistics.

* Alvaro Forteza, Ignacio Alvarez, Natalia da Silva, and Ianina Rossi. (2012) "Incentivos y patrones de retiro en Uruguay". Estudios Económicos 2012, 27 (2).

* Alvaro Forteza, Ignacio Alvarez, Natalia da Silva, and Ianina Rossi. (2010). "Qué Incentivos al Retiro Genera la Seguridad Social? El Caso Uruguayo". Latin American Journal of Economics, Instituto de Economía. Pontificia Universidad Católica de Chile., vol. 47(136), pages 217-247.

* Alvaro Forteza, Ignacio Alvarez, Natalia da Silva, and Ianina Rossi. (2009) "El retiro de los trabajadores uruguayos y la seguridad social", Revista de Economía, Banco Central del Uruguay, Vol. 16, No. 2.

# Poster presentations:

* Ignacio Alvarez, and Jarad Niemi. (Poster) Bayesian Inference of a covariance matrix. 26th Conference on Applied Statistics in Agriculture, Kansas State University, Manhattan, Kansas 2014.
* Natalia da Silva, and Ignacio Alvarez. (Poster) ``Clique and Clicks. Exploring the soul of the community''. 2013 Joint Statistical Meetings, Data-Expo competition. Montreal, Canada, 2013.